language: python
python: "2.7"
before_install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -q -N -t 3 -c travis.cfg install download install
  - bin/buildout -q -N -t 3 -c travis.cfg
script: bin/test